---

- name: Dnsmasq - Installing application.
  community.general.homebrew:
    name: dnsmasq
    state: present
    update_homebrew: true

- name: Dnsmasq - Get System etc Directory.
  ansible.builtin.shell: >
    echo "$(brew --prefix)/etc/"
  register: etc_config_directory
  changed_when: false

- name: Dnsmasq - Copying dnsmasq configuration.
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ etc_config_directory.stdout | trim }}/dnsmasq.conf"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0644

- name: Dnsmasq - Ensuring resolver directory exists.
  ansible.builtin.file:
    dest: /etc/resolver
    state: directory
    mode: 0755
  become: true

- name: Dnsmasq - Configuring Dnsmasq Resolver.
  ansible.bultin.copy:
    src: resolver.conf
    dest: "/etc/resolver/{{ item.domain }}"
    mode: 0644
  loop: "{{ dnsmasq_hosts }}"
  become: true

- name: Dnsmasq - Deploying Dnsmasq Service.
  ansible.builtin.copy:
    src: "{{ homebrew_prefix }}/opt/dnsmasq/homebrew.mxcl.dnsmasq.plist"
    dest: "/Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist"
    mode: 0644
  become: true

- name: Dnsmasq - Ensuring that Dnsmasq Service is Running.
  community.general.launchd:
    name: homebrew.mxcl.dnsmasq
    enabled: true
    state: started
