---

- name: Installing Dnsmasq
  homebrew:
    name: dnsmasq
    state: present
  notify:
    - Restart Dnsmasq

- name: Copying dnsmasq configuration.
  template:
    src: dnsmasq.conf.j2
    dest: "{{ homebrew_prefix }}/etc/dnsmasq.conf"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0644
  notify:
    - Restart Dnsmasq

- name: Ensuring resolver directory exists
  file: dest=/etc/resolver state=directory mode=0755
  become: true

- name: Configuring Dnsmasq Resolver
  copy:
    src: resolver.conf
    dest: "/etc/resolver/{{ item.domain }}"
    mode: 0644
  loop: "{{ dnsmasq_hosts }}"
  become: true

- name: Starting Dnsmasq Service
  community.general.launchd:
    name: homebrew.mxcl.dnsmasq
    enabled: true
    state: started
