---

name: release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      shouldPublishImage:
        description: 'Should publish image to Ansible Galaxy? (yes/no)'
        required: false
        default: 'no'

jobs:
  ci:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          set -eux

          pip install ansible
          pip install yamllint
          pip install ansible-lint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible lint
        working-directory: tests
        run: ansible-lint test.yml -c ../.ansible-lint

      - name: Verify syntax
        working-directory: tests
        run: ansible-playbook test.yml --syntax-check

      - name: Run Role
        run: |
          ansible-galaxy install ./
          cat >> playbook.yml <<EOL
          ---
          - name: Run apache
          hosts: all
          roles:
            - apache-role
          EOL

          cat >> hosts <<EOL
          192.168.0.10
          EOL
          ansible-playbook playbook.yml -i hosts

  publish:
    if: github.event.inputs.shouldPublishImage == 'yes' || github.ref == 'refs/heads/master'
    needs: ci
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          path: wayofdev
